# Page settings
baseURL = ""
relativeURLs = true
title = "SANDBOX ENVIRONMENT"
languageCode = "en-us"
publishDir = "../docs"
pygmentsCodeFences = true
pygmentsStyle = "manni"

[params]
  # Meta
  author = ""
  description = ""
  email = ""
  ghrepo = "https://github.com/mattermost/mattermost-documentation/"

  [params.mailinglist]
    enable = false

  [params.notification]
    enable = false
    url = "blog/repo-split"
    text = "This is a sample announcement"

  [params.search]
    enable = true

  [params.sidebar]
  [[params.sidebar.item]]
    name = "docs"
    displayName = "Docs"
    draft = true

  [[params.sidebar.item]]
    name = "education"
    displayName = "Education"
    draft = true

  [[params.sidebar.item]]
    name = "community"
    displayName = "Community"
    draft = false

  [[params.sidebar.item]]
    name = "support"
    displayName = "Support"
    draft = false

  # Navigation
  [params.navigation]
    brand = "This is a sandbox environment. Please see docs.mattermost.com for Mattermost documentation"
    home = "Home"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/docs/main"
      name = "Docs"
      weight = 1

    [[menu.postpend]]
      url = "/education/main"
      name = "Education"
      weight = 2

    [[menu.postpend]]
      url = "/community/main"
      name = "Community"
      weight = 3

    [[menu.postpend]]
      url = "/support/main"
      name = "Support"
      weight = 4

    # Workaround to add draft status to menu items
    [[params.navigation.drafts]]
      Docs = false

  # Hero section
  [params.hero]
    title = "All your Mattermost help and support needs"
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  [[params.intro.item]]
    title = "Docs"
    description = "Technical product documentation for end users, administrators and developers."
    url = "docs/main"
    button = "Explore Docs"
    icon = "/img/contribute-icon.svg"
    draft = false

  [[params.intro.item]]
    title = "Education"
    description = "Technical articles, guides, videos, and courses."
    url = "education/main"
    button = "Explore Education"
    icon = "/img/integrate-icon.svg"
    draft = false

  [[params.intro.item]]
    title = "Community"
    description = "Contributor documentation and relevant community communications."
    url = "community/main"
    button = "Explore Community"
    icon = "/img/extend-icon.svg"
    draft = false

  [[params.intro.item]]
    title = "Support"
    description = "Self-service support content, including knowledge-based FAQs."
    url = "internal"
    button = "support/main"
    icon = "/img/extend-icon.svg"
    draft = false

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"

  # Footer section
  [params.footer]
    enable = true
    twitter = 'https://twitter.com/mattermost'
    facebook = 'https://www.facebook.com/Mattermost-2300985916642531/'
    youtube = 'https://www.youtube.com/channel/UCNR05H72hi692y01bWaFXNA'
    copyright = '&copy; Mattermost, Inc. All Rights Reserved.'

# Allows html in Hugo >= v0.60.0.  See Github issue #506.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
