# Page settings
baseurl = "localhost:1313"
title = "SANDBOX ENVIRONMENT"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "SANDBOX ENVIRONMENT"
    home = "Home"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/contribute/"
      name = "Docs"
      weight = 10

  # Hero section
  [params.hero]
    title = "This is a sandbox environment. Please see docs.mattermost.com for Mattermost documentation"
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Docs"
    description = "Technical product documentation for end users, administrators and developers."
    url = "/contribute/"
    button = "Explore Docs"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Education"
    description = "Technical articles, guides, videos, and courses."
    url = "/integrate"
    button = "Explore Education"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Community"
    description = "Contributor documentation and relevant community communications."
    url = "/extend"
    button = "Explore Community"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [[params.intro.item]]
    title = "Support"
    description = "Self-service support content, including knowledge-based FAQs."
    url = "/internal"
    button = "Explore Support"
    icon = "icon-rocket"
    img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"

  # Footer section
  [params.footer]
    enable = true
    twitter = 'https://twitter.com/mattermost'
    facebook = 'https://www.facebook.com/Mattermost-2300985916642531/'
    youtube = 'https://www.youtube.com/channel/UCNR05H72hi692y01bWaFXNA'
    copyright = '&copy; Mattermost, Inc. All Rights Reserved.'
